import { siteConfig } from "@/lib/site-config";

/**
 * Share-card imagery, normalised for the crawlers that actually fetch it.
 *
 * X's card renderer is the strictest of the bunch and fails *silently* — a
 * card with no preview looks identical to a card whose image 404'd. Three
 * things trip it up here:
 *
 *  1. Relative URLs. Next resolves `openGraph.images` against `metadataBase`,
 *     but `twitter:image` is worth emitting fully-qualified regardless.
 *  2. SVG. Articles saved without a featured image fall back to
 *     `/logo-mark.svg`, and X refuses SVG (and AVIF) outright — only JPEG,
 *     PNG, WEBP and GIF render. That is the common case for a blank preview.
 *  3. Anything that isn't an http(s) URL — `data:`/`blob:` values that can
 *     leak in from an editor paste.
 *
 * Any of those falls back to the generated `/opengraph-image` PNG, so every
 * page ships a card that renders instead of nothing at all.
 */

/** Generated by `app/opengraph-image.tsx`. Always a 1200x630 PNG. */
const FALLBACK = {
  url: siteConfig.ogImage,
  width: 1200,
  height: 630,
  alt: `${siteConfig.name} — ${siteConfig.tagline}`,
  type: "image/png",
} as const;

/** Formats X will not render, so they can never be the card image. */
const UNSUPPORTED = /\.(svgz?|avif|bmp|tiff?|heif|heic|ico)$/i;

const MIME: Record<string, string> = {
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".png": "image/png",
  ".webp": "image/webp",
  ".gif": "image/gif",
};

export interface SocialImage {
  url: string;
  width: number;
  height: number;
  alt: string;
  type?: string;
}

/**
 * Resolve a stored image path to an absolute URL a crawler can fetch, or
 * `null` when it is unusable as a share card.
 */
function absolute(src: string | null | undefined): URL | null {
  const trimmed = src?.trim();
  if (!trimmed) return null;
  let url: URL;
  try {
    url = new URL(trimmed, siteConfig.url);
  } catch {
    return null;
  }
  // `data:`, `blob:`, and anything else a crawler can't request.
  if (url.protocol !== "https:" && url.protocol !== "http:") return null;
  if (UNSUPPORTED.test(url.pathname)) return null;
  return url;
}

/**
 * Build the image descriptor shared by `openGraph.images` and
 * `twitter.images`. `dimensions` describe the source image when known; they
 * are ignored when the fallback card is substituted.
 */
export function socialImage(
  src: string | null | undefined,
  alt: string,
  dimensions?: { width: number; height: number },
  /**
   * Card to use when `src` is unusable. Pages that can generate something
   * specific to the content (articles render their own headline card) pass it
   * here so a share preview is never the generic site image.
   */
  fallback?: { url: string; alt: string }
): SocialImage {
  const url = absolute(src);
  if (!url) {
    return fallback
      ? { ...FALLBACK, url: fallback.url, alt: fallback.alt }
      : { ...FALLBACK };
  }

  const dot = url.pathname.lastIndexOf(".");
  const ext = dot === -1 ? "" : url.pathname.slice(dot).toLowerCase();
  return {
    url: url.toString(),
    width: dimensions?.width ?? 1200,
    height: dimensions?.height ?? 630,
    alt: alt.trim() || FALLBACK.alt,
    ...(MIME[ext] ? { type: MIME[ext] } : {}),
  };
}

/** `@handle` from a profile URL, for `twitter:site` / `twitter:creator`. */
export function xHandle(profileUrl: string | undefined): string | undefined {
  if (!profileUrl) return undefined;
  const raw = profileUrl.trim();
  if (!raw) return undefined;
  const name = raw.startsWith("@")
    ? raw.slice(1)
    : raw.replace(/^https?:\/\/(www\.)?(twitter|x)\.com\//i, "").split(/[/?#]/)[0];
  return /^[A-Za-z0-9_]{1,15}$/.test(name) ? `@${name}` : undefined;
}

/** The Journal's own account, used as `twitter:site` on every page. */
export const SITE_X_HANDLE = xHandle(siteConfig.links.x);

/**
 * Worth being explicit about what reads what, because it is not five
 * standards — it is one:
 *
 *   - **Facebook** — Open Graph (it defined it). Note it only honours `og:*`
 *     and `article:*` on `<meta property=…>`; `name=` is ignored, which is
 *     why these go through Next's typed `openGraph` field and not `other`.
 *   - **Bluesky, Substack, LinkedIn, Slack, Discord** — plain Open Graph.
 *     None define tags of their own; `og:image` is the whole story.
 *   - **X** — Open Graph, overridden by `twitter:*` where present.
 *   - **Instagram** — renders no link previews at all. Links aren't tappable
 *     in captions; profile and Story links use Open Graph when they preview.
 *
 * So the coverage question is never "which tags" — every one of them reads
 * the same `og:image`. It's whether that one URL is absolute, public, and in
 * a format the crawlers accept, which is what `socialImage` guarantees.
 */

/**
 * The `twitter` metadata block. Every page routes through this so the card
 * type, site handle, and image alt text can never drift apart.
 */
export function twitterMetadata({
  title,
  description,
  image,
  creator,
}: {
  title: string;
  description?: string;
  image: SocialImage;
  creator?: string;
}) {
  return {
    card: "summary_large_image" as const,
    site: SITE_X_HANDLE,
    creator: creator ?? SITE_X_HANDLE,
    title,
    description,
    // X reads only the URL and alt text; dimensions come from the fetch.
    images: [{ url: image.url, alt: image.alt }],
  };
}
